// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtDHM8hVSDO986hOwHN6XvOGqbsn0xcdQ',
    appId: '1:649174116725:web:838d4c4b332209b0e14b3c',
    messagingSenderId: '649174116725',
    projectId: 'unique-tour-app',
    authDomain: 'unique-tour-app.firebaseapp.com',
    storageBucket: 'unique-tour-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo3holkppUxJ8xoVnlJeHQJZZaiDntc1Q',
    appId: '1:649174116725:android:2447d8a57d4e2e7ee14b3c',
    messagingSenderId: '649174116725',
    projectId: 'unique-tour-app',
    storageBucket: 'unique-tour-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApswSdirZm8dACwLejzUsRbzwvC_tIH4o',
    appId: '1:649174116725:ios:bc3ecd350953e095e14b3c',
    messagingSenderId: '649174116725',
    projectId: 'unique-tour-app',
    storageBucket: 'unique-tour-app.firebasestorage.app',
    iosBundleId: 'com.example.tourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApswSdirZm8dACwLejzUsRbzwvC_tIH4o',
    appId: '1:649174116725:ios:bc3ecd350953e095e14b3c',
    messagingSenderId: '649174116725',
    projectId: 'unique-tour-app',
    storageBucket: 'unique-tour-app.firebasestorage.app',
    iosBundleId: 'com.example.tourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtDHM8hVSDO986hOwHN6XvOGqbsn0xcdQ',
    appId: '1:649174116725:web:ae4f7b417f346443e14b3c',
    messagingSenderId: '649174116725',
    projectId: 'unique-tour-app',
    authDomain: 'unique-tour-app.firebaseapp.com',
    storageBucket: 'unique-tour-app.firebasestorage.app',
  );
}
